title: Jim Merritt, Designer & Front End Developer
email: merritt.ja@gmail.com
description: >
  Jim Merritt's resume website, built in Jekyll and hosted through GitHub pages.
baseurl: ""
url: "http://jimmerritt.io"
#twitter_username: thirdactpub
github_username:  JimMerritt

markdown: kramdown
